name: Build and test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
jobs:
  verify:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Need all the history for git describe --tags to work
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.3'
      - name: Static checks
        run: make verify
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Need all the history for git describe --tags to work
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.3'
      - name: Unit tests
        run: make test
  e2e:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Need all the history for git describe --tags to work
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.3'
      - name: Install kubectl
        run: |
          # Download & verify kubectl
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.2/bin/linux/amd64/kubectl
          echo "3ff48e12f9c768ad548e4221d805281ea28dfcda5c18b3cd1797fe37aee3012e  kubectl" | sha256sum -c
          # Mark it executable & move to /bin
          sudo chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin
      - name: Install kustomize
        run: |
          curl -L -o /tmp/kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.5.4/kustomize_v3.5.4_linux_amd64.tar.gz
          echo "5cdeb2af81090ad428e3a94b39779b3e477e2bc946be1fe28714d1ca28502f6a  /tmp/kustomize.tar.gz" | sha256sum -c
          sudo tar -C /usr/local/bin -x -f /tmp/kustomize.tar.gz
      - name: End to end tests
        run: make e2e-kind TEST_PARALLEL_E2E=1 E2E_ARTIFACTS_DIRECTORY=/tmp/etcd-e2e
      - name: Export Logs
        run: make kind-export-logs E2E_ARTIFACTS_DIRECTORY=/tmp/etcd-e2e
        if: always()
      - name: Upload Logs
        uses: actions/upload-artifact@v1
        with:
          name: e2e-logs
          path: /tmp/etcd-e2e
