name: Release Docker images
on:
  push:
    branches:
      - master
    tags:
      - "*"
  # Temporary to test
  pull_request:
    branches:
      - "*"
jobs:
  e2e:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Need all the history for git describe --tags to work
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.3'
      - name: Build and push Docker image
        run: make docker-build docker-push DOCKER_REPO=docker.pkg.github.com/improbable-eng/etcd-cluster-operator
